---
booktitle: Proceedings of The 27th International Conference on Artificial Intelligence
  and Statistics
shortname: AISTATS
volume: '238'
year: '2024'
start: 2024-05-02
end: 2024-05-04
location: Valencia, Spain
published: 2024-04-18
conference_number: '27'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: AISTATS-2024
month: 0
cycles: false
bibtex_editor: Dasgupta, Sanjoy and Mandt, Stephan and Li, Yingzhen
editor:
- given: Sanjoy
  family: Dasgupta
- given: Stephan
  family: Mandt
- given: Yingzhen
  family: Li
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 27th International Conference on Artificial Intelligence and Statistics
    Held in Palau de Congressos, Valencia, Spain on 02-04 May 2024

  Published as Volume 238 by the Proceedings of Machine Learning Research on 18 April 2024.

  Volume Edited by:
    Sanjoy Dasgupta
    Stephan Mandt
    Yingzhen Li

  Series Editors:
    Neil D. Lawrence
date_str: 02--04 May
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v238"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v238
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v238
email: ''
conference:
  name: International Conference on Artificial Intelligence and Statistics
  url: http://aistats.org/aistats2024/
  location: Palau de Congressos, Valencia, Spain
  dates:
  - 2024-05-02
  - 2024-05-03
  - 2024-05-04
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v238/aistats24.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v238/aistats24.bib
